name: Build and Release

env:
  PACKAGE_NAME: morrow.mojopkg
  MORROW_SRC: morrow

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          curl https://get.modular.com | MODULAR_AUTH=${{ secrets.MODULAR_AUTH }} sh - 
          modular auth ${{ secrets.MODULAR_AUTH }}
          python3 -m venv ~/max-venv && source ~/max-venv/bin/activate
          modular install max
          MAX_PATH=$(modular config max.path) \
            && python3 -m pip install --find-links $MAX_PATH/wheels max-engine
          MAX_PATH=$(modular config max.path) \
            && BASHRC=$( [ -f "$HOME/.bash_profile" ] && echo "$HOME/.bash_profile" || echo "$HOME/.bashrc" ) \
            && echo 'export MODULAR_HOME="'$HOME'/.modular"' >> "$BASHRC" \
            && echo 'export PATH="'$MAX_PATH'/bin:$PATH"' >> "$BASHRC" \
            && source "$BASHRC"
      - name: Build
        run: |
          MAX_PATH=$(modular config max.path) \
            && BASHRC=$( [ -f "$HOME/.bash_profile" ] && echo "$HOME/.bash_profile" || echo "$HOME/.bashrc" ) \
            && echo 'export MODULAR_HOME="'$HOME'/.modular"' >> "$BASHRC" \
            && echo 'export PATH="'$MAX_PATH'/bin:$PATH"' >> "$BASHRC" \
            && source "$BASHRC"
          mojo package ${{ env.MORROW_SRC }} -o ${{ github.workspace }}/${{ env.PACKAGE_NAME }}
      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PACKAGE_NAME }}
          path: ${{ github.workspace }}/${{ env.PACKAGE_NAME }}
